db.ventas.drop()
db.ventas.insertMany([
    {
        Articulo_vendido: "Chirimoyas",
        Categoria: "Frutas",
        Precio_unitario: 3.44,
        Número_de_unidades: 150,
        Fecha_de_la_venta: new Date("2020-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.97,
        Cliente: "Fruteria_Luis",
        Vendedo: "MercaSevilla",
    },
    {
        Articulo_vendido: "Limones",
        Categoria: "Frutas",
        Precio_unitario: 1.20,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2020-12-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.78,
        Cliente: "Fruteria_Luis",
        Vendedo: "MercaSevilla",
    },
    {
        Articulo_vendido: "Mandarina Clementina",
        Categoria: "Frutas",
        Precio_unitario: 2.50,
        Número_de_unidades: 30,
        Fecha_de_la_venta: new Date("2020-12-9"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.77,
        Cliente: "Frutópolis",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Manzana Golden",
        Categoria: "Frutas",
        Precio_unitario: 1.25,
        Número_de_unidades: 40,
        Fecha_de_la_venta: new Date("2020-11-28"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.70,
        Cliente: "Fruteria_la_Mari",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Manzana Roja",
        Categoria: "Frutas",
        Precio_unitario: 1.10,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2019-11-27"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.65,
        Cliente: "Frutópolis",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Naranja Navelina",
        Categoria: "Frutas",
        Precio_unitario: 1.10,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2020-11-20"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.52,
        Cliente: "Frutero Emilio",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "PeraBlanquilla",
        Categoria: "Frutas",
        Precio_unitario: 1.50,
        Número_de_unidades: 56,
        Fecha_de_la_venta: new Date("2020-11-16"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.25,
        Cliente: "Frutópolis",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Piñas",
        Categoria: "Frutas",
        Precio_unitario: 2.50,
        Número_de_unidades: 20,
        Fecha_de_la_venta: new Date("2020-11-6"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.10,
        Cliente: "Fruteria_la_Mari",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Plátanos",
        Categoria: "Frutas",
        Precio_unitario: 0.98,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2018-10-25"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.70,
        Cliente: "Fruteria_Luis",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Uba Blanca",
        Categoria: "Frutas",
        Precio_unitario: 2.00,
        Número_de_unidades: 156,
        Fecha_de_la_venta: new Date("2020-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.70,
        Cliente: "Fruteria_la_Mari",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Alcachofas",
        Categoria: "Hortalizas",
        Precio_unitario: 2.03,
        Número_de_unidades: 56,
        Fecha_de_la_venta: new Date("2020-12-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.50,
        Cliente: "Frutero_Emilio",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Cebollas Grano de Oro",
        Categoria: "Hortalizas",
        Precio_unitario: 0.39,
        Número_de_unidades: 25,
        Fecha_de_la_venta: new Date("2020-12-20"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.30,
        Cliente: "Frutero_la_Mari",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Coliflor",
        Categoria: "Hortalizas",
        Precio_unitario: 1.56,
        Número_de_unidades: 16,
        Fecha_de_la_venta: new Date("2018-12-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.65,
        Cliente: "Fruteria_Luis",
        Vendedor: "MercaBilbao",
    },
    {
        Articulo_vendido: "Escarola",
        Categoria: "Hortalizas",
        Precio_unitario: 0.90,
        Número_de_unidades: 66,
        Fecha_de_la_venta: new Date("2020-11-22"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.60,
        Cliente: "Frutero_Frutópolis",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Judías Verdes",
        Categoria: "Hortalizas",
        Precio_unitario: 2.40,
        Número_de_unidades: 80,
        Fecha_de_la_venta: new Date("2020-11-25"),
        Precio_unitario_de_la_compra_de_la_empresa: 2.00,
        Cliente: "Frutero_la_Mari",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Lechugas",
        Categoria: "Hortalizas",
        Precio_unitario: 0.60,
        Número_de_unidades: 70,
        Fecha_de_la_venta: new Date("2020-11-16"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.30,
        Cliente: "Frutópolis",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Lombarda",
        Categoria: "Hortalizas",
        Precio_unitario: 0.50,
        Número_de_unidades: 25,
        Fecha_de_la_venta: new Date("2019-10-26"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.30,
        Cliente: "Frutero__la_Mari",
        Vendedor: "MercaBilbao",
    },
    {
        Articulo_vendido: "Patatas Calidad",
        Categoria: "Hortalizas",
        Precio_unitario: 0.48,
        Número_de_unidades: 150,
        Fecha_de_la_venta: new Date("2020-10-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.25,
        Cliente: "Frutópolis",
        Vendedor: "MercaBilbao",
    },
    {
        Articulo_vendido: "Pimientos Verdes",
        Categoria: "Hortalizas",
        Precio_unitario: 1,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2020-12-15"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.60,
        Cliente: "Fruteria_Luis",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Tomate Maduro",
        Categoria: "Hortalizas",
        Precio_unitario: 0.87,
        Número_de_unidades: 200,
        Fecha_de_la_venta: new Date("2020-12-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.40,
        Cliente: "Frutero_Emilio",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Tomate verde",
        Categoria: "Hortalizas",
        Precio_unitario: 0.93,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2018-10-26"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.80,
        Cliente: "Frutópolis",
        Vendedor: "MercaValencia",
    },
    {
        Articulo_vendido: "Zanahorias",
        Categoria: "Hortalizas",
        Precio_unitario: 0.57,
        Número_de_unidades: 120,
        Fecha_de_la_venta: new Date("2020-11-25"),
        Precio_unitario_de_la_compra_de_la_empresa: 0.43,
        Cliente: "Frutero_Luis",
        Vendedor: "MercaCabarna",
    },
    {
        Articulo_vendido: "Bacaladilla",
        Categoria: "Pescado Fresco",
        Precio_unitario: 3.00,
        Número_de_unidades: 20,
        Fecha_de_la_venta: new Date("2020-12-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 2.80,
        Cliente: "Pescaderia_Ruben",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Besugo",
        Categoria: "Pescado Fresco",
        Precio_unitario: 28.00,
        Número_de_unidades: 5,
        Fecha_de_la_venta: new Date("2020-12-15"),
        Precio_unitario_de_la_compra_de_la_empresa: 18.00,
        Cliente: "El_Nemo_feliz",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Boquerón extra",
        Categoria: "Pescado Fresco",
        Precio_unitario: 6.00,
        Número_de_unidades: 30,
        Fecha_de_la_venta: new Date("2019-11-30"),
        Precio_unitario_de_la_compra_de_la_empresa: 4.80,
        Cliente: "Marea_Alta",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Calamar",
        Categoria: "Pescado Fresco",
        Precio_unitario: 13.00,
        Número_de_unidades: 20,
        Fecha_de_la_venta: new Date("2020-12-3"),
        Precio_unitario_de_la_compra_de_la_empresa: 10.00,
        Cliente: "El_Nemo_feliz",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Chirla",
        Categoria: "Pescado Fresco",
        Precio_unitario: 6.00,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2020-12-20"),
        Precio_unitario_de_la_compra_de_la_empresa: 5.22,
        Cliente: "Marea_Alta",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Gamba",
        Categoria: "Pescado Fresco",
        Precio_unitario: 95.00,
        Número_de_unidades: 200,
        Fecha_de_la_venta: new Date("2019-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 33.00,
        Cliente: "Pescaderia_Ruben",
        Vendedor: "MercaMercaBilbao",
    },
    {
        Articulo_vendido: "Langostino",
        Categoria: "Pescado Fresco",
        Precio_unitario: 28.00,
        Número_de_unidades: 150,
        Fecha_de_la_venta: new Date("2020-12-17"),
        Precio_unitario_de_la_compra_de_la_empresa: 24.33,
        Cliente: "Agua_Clara",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Lubina",
        Categoria: "Pescado Fresco",
        Precio_unitario: 6.50,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2020-11-22"),
        Precio_unitario_de_la_compra_de_la_empresa: 4.80,
        Cliente: "El_Nemo_feliz",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Mejillón",
        Categoria: "Pescado Fresco",
        Precio_unitario: 1.80,
        Número_de_unidades: 120,
        Fecha_de_la_venta: new Date("2018-11-12"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.50,
        Cliente: "Agua_Clara",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Merluza",
        Categoria: "Pescado Fresco",
        Precio_unitario: 12.00,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2020-11-2"),
        Precio_unitario_de_la_compra_de_la_empresa: 8.50,
        Cliente: "Marea_Alta",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Pescadilla",
        Categoria: "Pescado Fresco",
        Precio_unitario: 11.50,
        Número_de_unidades: 70,
        Fecha_de_la_venta: new Date("2020-10-26"),
        Precio_unitario_de_la_compra_de_la_empresa: 4.58,
        Cliente: "Pescaderia_Ruben",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Salmón",
        Categoria: "Pescado Fresco",
        Precio_unitario: 6.00,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2018-10-15"),
        Precio_unitario_de_la_compra_de_la_empresa: 4.98,
        Cliente: "El_Nemo_feliz",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Sardina",
        Categoria: "Pescado Fresco",
        Precio_unitario: 4.50,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2020-10-2"),
        Precio_unitario_de_la_compra_de_la_empresa: 2.80,
        Cliente: "Pescaderia_Ruben",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Trucha",
        Categoria: "Pescado Fresco",
        Precio_unitario: 4.40,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2018-12-20"),
        Precio_unitario_de_la_compra_de_la_empresa: 4.20,
        Cliente: "El_Nemo_feliz",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Calamar",
        Categoria: "Pescado Congelado",
        Precio_unitario: 4.65,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2020-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 3.75,
        Cliente: "Pescaderia_Ruben",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Cigala",
        Categoria: "Pescado Congelado",
        Precio_unitario: 42.00,
        Número_de_unidades: 25,
        Fecha_de_la_venta: new Date("2019-12-18"),
        Precio_unitario_de_la_compra_de_la_empresa: 32.50,
        Cliente: "Marea_Alta",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Gamba",
        Categoria: "Pescado Congelado",
        Precio_unitario: 25.00,
        Número_de_unidades: 60,
        Fecha_de_la_venta: new Date("2020-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 21.00,
        Cliente: "El_Nemo_feliz",
        Vendedor: "MercaBilbao",
    },
    {
        Articulo_vendido: "Langostino",
        Categoria: "Pescado Congelado",
        Precio_unitario: 12.00,
        Número_de_unidades: 56,
        Fecha_de_la_venta: new Date("2020-12-15"),
        Precio_unitario_de_la_compra_de_la_empresa: 9.50,
        Cliente: "Agua_Clara",
        Vendedor: "MercaBilbao",
    },
    {
        Articulo_vendido: "Merluza",
        Categoria: "Pescado Congelado",
        Precio_unitario: 7.00,
        Número_de_unidades: 40,
        Fecha_de_la_venta: new Date("2018-11-28"),
        Precio_unitario_de_la_compra_de_la_empresa: 5.80,
        Cliente: "Pescaderia_Ruben",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Ovino-Casquería",
        Categoria: "Carnes",
        Precio_unitario: 1.52,
        Número_de_unidades: 300,
        Fecha_de_la_venta: new Date("2020-12-10"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.20,
        Cliente: "Carniceria_Paco",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Ovino-Lechal",
        Categoria: "Carnes",
        Precio_unitario: 8.75,
        Número_de_unidades: 200,
        Fecha_de_la_venta: new Date("2018-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 6.00,
        Cliente: "Carnes_Paqui",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Ovino-Recental",
        Categoria: "Carnes",
        Precio_unitario: 6.98,
        Número_de_unidades: 100,
        Fecha_de_la_venta: new Date("2020-12-17"),
        Precio_unitario_de_la_compra_de_la_empresa: 5.00,
        Cliente: "Carnes_Paqui",
        Vendedor: "MercaBilbao",
    },
    {
        Articulo_vendido: "Porcino-Casquería",
        Categoria: "Carnes",
        Precio_unitario: 1.16,
        Número_de_unidades: 500,
        Fecha_de_la_venta: new Date("2019-12-15"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.00,
        Cliente: "Carnicos_Juan",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Porcino-Cerdo blanco",
        Categoria: "Carnes",
        Precio_unitario: 2.03,
        Número_de_unidades: 50,
        Fecha_de_la_venta: new Date("2020-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.50,
        Cliente: "Carniceria_Paco",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Porcino-Cochinillo",
        Categoria: "Carnes",
        Precio_unitario: 15.00,
        Número_de_unidades: 120,
        Fecha_de_la_venta: new Date("2019-12-17"),
        Precio_unitario_de_la_compra_de_la_empresa: 12.50,
        Cliente: "Carnicos_Juan",
        Vendedor: "MercaMadrid",
    },
    {
        Articulo_vendido: "Vacuno-Añojo",
        Categoria: "Carnes",
        Precio_unitario: 4.03,
        Número_de_unidades: 30,
        Fecha_de_la_venta: new Date("2020-10-12"),
        Precio_unitario_de_la_compra_de_la_empresa: 2.52,
        Cliente: "Carnes_Paqui",
        Vendedor: "MercaBarna",
    },
    {
        Articulo_vendido: "Vacuno-Casqueria",
        Categoria: "Carnes",
        Precio_unitario: 2.17,
        Número_de_unidades: 60,
        Fecha_de_la_venta: new Date("2020-11-12"),
        Precio_unitario_de_la_compra_de_la_empresa: 1.50,
        Cliente: "Carnicos_Juan",
        Vendedor: "MercaSevilla",
    },
    {
        Articulo_vendido: "Vacuno-Ternera",
        Categoria: "Carnes",
        Precio_unitario: 4.39,
        Número_de_unidades: 56,
        Fecha_de_la_venta: new Date("2019-12-21"),
        Precio_unitario_de_la_compra_de_la_empresa: 3.10,
        Cliente: "Carnes_Paqui",
        Vendedor: "MercaSevilla",
    },
]);